import type { BaseToolDebugStackFrame, BaseToolDebugVariable } from "../../../../../agentCore_executionEngine/basic_toolLayer/baseTools/baseToolExecutorPort.js";
import type { CodeToolAuditEvent, CodeToolResult } from "../../_shared/baseToolAdapter.js";

export type CodeDebugCaptureStateBoundary = "input" | "contract" | "governance" | "scope" | "provider";
export type CodeDebugCaptureTargetKind = "debug-session" | "process" | "test-run" | "workspace";
export type CodeDebugCaptureTarget = { kind?: CodeDebugCaptureTargetKind; id?: string; cwd?: string };
export type CodeDebugCaptureOptions = { includeStack?: boolean; includeVariables?: boolean; includeBreakpoints?: boolean; maxVariables?: number };
export type CodeDebugGate = { accepted?: boolean; allowed?: boolean; reason?: string };
export type CodeDebugContext = { runtimeId?: string; sessionId?: string; invocationId?: string; dryRun?: boolean; guard?: CodeDebugGate; requestedScopes?: readonly string[]; allowedScopes?: readonly string[]; auditMetadata?: Readonly<Record<string, unknown>> };
export type CodeDebugCaptureStateRequest = { context?: CodeDebugContext; runtimeId?: string; sessionId?: string; invocationId?: string; target?: CodeDebugCaptureTarget; capture?: CodeDebugCaptureOptions; requestedScopes?: readonly string[]; allowedScopes?: readonly string[]; dryRun?: boolean; guard?: CodeDebugGate; contract?: CodeDebugGate; governance?: CodeDebugGate; provider?: CodeDebugCaptureStateProvider };
export type CodeDebugCaptureStateErrorCode = "MISSING_RUNTIME_ID" | "MISSING_SESSION_ID" | "MISSING_TARGET" | "MISSING_TARGET_ID" | "INVALID_CAPTURE_LIMIT" | "CONTRACT_REJECTED" | "GOVERNANCE_REJECTED" | "SCOPE_DENIED" | "REAL_DEBUG_CAPTURE_NOT_ALLOWED" | "PROVIDER_UNAVAILABLE" | "PROVIDER_FAILURE";
export type CodeDebugCaptureStateError = { code: CodeDebugCaptureStateErrorCode; message: string; boundary: CodeDebugCaptureStateBoundary; safeForRuntimeInspection: true; internalDetailExposed: false };
export type CodeDebugCaptureStatePlan = { toolName: "code.debugCaptureState"; runtimeId: string; sessionId: string; invocationId: string; target: { kind: CodeDebugCaptureTargetKind; id: string; cwd?: string }; permissions: readonly ["debug:read"]; capture: Required<CodeDebugCaptureOptions>; execution: { dryRun: true; captured: false; unsafeSideEffects: false }; audit: { governanceRequired: true; tapHandoffReady: true }; storage: { logic: { persisted: false }; records: readonly { toolName: "code.debugCaptureState" }[] } };
export type CodeDebugCaptureStateOutput = { kind: "agentCore.basicTool.code.debugCaptureState.output"; runtimeId: string; sessionId: string; invocationId: string; target: { kind: CodeDebugCaptureTargetKind; id: string; cwd?: string }; capture: Required<CodeDebugCaptureOptions>; runtimeEntry: { owner: "runtime"; port: "BaseToolExecutorPort.debug.captureState"; method: "captureState" }; dryRun: boolean; providerCalled: boolean; state: "running" | "paused" | "stopped" | "unknown" | "planned"; stack: readonly BaseToolDebugStackFrame[]; variables: readonly BaseToolDebugVariable[]; breakpoints: readonly Readonly<Record<string, unknown>>[]; truncated: boolean; unsafeSideEffects: false };
export type CodeDebugCaptureStateResult = { ok: true; plan: CodeDebugCaptureStatePlan; events: readonly string[] } | { ok: false; error: CodeDebugCaptureStateError; events: readonly string[] };
export type CodeDebugCaptureStateProvider = (request: { target: { kind: CodeDebugCaptureTargetKind; id: string; cwd?: string }; capture: Required<CodeDebugCaptureOptions> }, context: CodeDebugContext) => Promise<{ state: "running" | "paused" | "stopped" | "unknown"; stack?: readonly BaseToolDebugStackFrame[]; variables?: readonly BaseToolDebugVariable[]; breakpoints?: readonly Readonly<Record<string, unknown>>[] }> | { state: "running" | "paused" | "stopped" | "unknown"; stack?: readonly BaseToolDebugStackFrame[]; variables?: readonly BaseToolDebugVariable[]; breakpoints?: readonly Readonly<Record<string, unknown>>[] };
type Normalized = Omit<CodeDebugCaptureStatePlan, "toolName" | "permissions" | "execution" | "audit" | "storage"> & { dryRun: boolean; context: CodeDebugContext };
export const codeDebugCaptureStateDescriptor = { toolName: "code.debugCaptureState", toolId: "code.debugCaptureState", toolFamily: "codeBase.debugCode", purpose: "capture debug state through runtime-owned debug support", dryRunOnly: false, unsafeSideEffects: false } as const;
function sv(value: unknown): string | undefined { return typeof value === "string" ? value : undefined; }
function blank(value: unknown): boolean { return typeof value !== "string" || value.trim().length === 0; }
function list(values: unknown): string[] { return Array.isArray(values) ? [...new Set(values.map((value) => (typeof value === "string" ? value.trim() : "")).filter(Boolean))] : []; }
function failure(code: CodeDebugCaptureStateErrorCode, message: string, boundary: CodeDebugCaptureStateBoundary): Extract<CodeDebugCaptureStateResult, { ok: false }> { return { ok: false, error: { code, message, boundary, safeForRuntimeInspection: true, internalDetailExposed: false }, events: ["agentCore.basicTool.code.debugCaptureState.rejected"] }; }
function auditEvent(type: string, normalized?: Pick<Normalized, "invocationId" | "dryRun" | "context">, metadata?: Readonly<Record<string, unknown>>): CodeToolAuditEvent { return { type, toolId: "code.debugCaptureState", invocationId: normalized?.invocationId ?? "code.debugCaptureState:unknown", dryRun: normalized?.dryRun ?? true, metadata: { ...(normalized?.context.auditMetadata ?? {}), ...(metadata ?? {}) } }; }
function toolFailure(code: CodeDebugCaptureStateErrorCode, message: string, boundary: CodeDebugCaptureStateBoundary, normalized?: Pick<Normalized, "invocationId" | "dryRun" | "context">): CodeToolResult<CodeDebugCaptureStateOutput, CodeDebugCaptureStateErrorCode> { return { ok: false, toolId: "code.debugCaptureState", error: { code, message, boundary, safeForRuntimeInspection: true, internalDetailExposed: false }, audit: [auditEvent("agentCore.basicTool.code.debugCaptureState.rejected", normalized, { code, boundary })], events: ["agentCore.basicTool.code.debugCaptureState.rejected"] }; }
function normalizeCapture(capture: CodeDebugCaptureOptions | undefined): Required<CodeDebugCaptureOptions> { return { includeStack: capture?.includeStack ?? true, includeVariables: capture?.includeVariables ?? false, includeBreakpoints: capture?.includeBreakpoints ?? true, maxVariables: capture?.maxVariables ?? 0 }; }
function rejected(...gates: readonly (CodeDebugGate | undefined)[]): CodeDebugGate | undefined { return gates.find((gate) => gate?.accepted === false || gate?.allowed === false); }
function approved(...gates: readonly (CodeDebugGate | undefined)[]): boolean { return gates.some((gate) => gate?.accepted === true || gate?.allowed === true); }
function normalize(request: CodeDebugCaptureStateRequest = {}): Normalized | Extract<CodeDebugCaptureStateResult, { ok: false }> {
  const context = request.context ?? {};
  const runtimeId = sv(context.runtimeId ?? request.runtimeId)?.trim() ?? "";
  const sessionId = sv(context.sessionId ?? request.sessionId)?.trim() ?? "";
  if (runtimeId.length === 0) return failure("MISSING_RUNTIME_ID", "code.debugCaptureState requires runtimeId", "input");
  if (sessionId.length === 0) return failure("MISSING_SESSION_ID", "code.debugCaptureState requires sessionId", "input");
  if (request.target === undefined || request.target.kind === undefined) return failure("MISSING_TARGET", "code.debugCaptureState requires a target kind", "input");
  if (blank(request.target.id)) return failure("MISSING_TARGET_ID", "code.debugCaptureState requires a target id", "input");
  if (request.capture?.maxVariables !== undefined && (!Number.isInteger(request.capture.maxVariables) || request.capture.maxVariables < 0)) return failure("INVALID_CAPTURE_LIMIT", "code.debugCaptureState maxVariables cannot be negative", "input");
  const deniedGate = rejected(request.contract, request.governance, request.guard, context.guard);
  if (deniedGate !== undefined) return failure(deniedGate === request.contract ? "CONTRACT_REJECTED" : "GOVERNANCE_REJECTED", deniedGate.reason ?? "code.debugCaptureState was rejected by runtime governance", deniedGate === request.contract ? "contract" : "governance");
  const requested = list(context.requestedScopes ?? request.requestedScopes);
  const allowed = list(context.allowedScopes ?? request.allowedScopes);
  const denied = requested.filter((scope) => !allowed.includes(scope));
  if (denied.length > 0) return failure("SCOPE_DENIED", `debug capture scope ${denied[0]} is outside runtime governance`, "scope");
  return { runtimeId, sessionId, invocationId: sv(context.invocationId ?? request.invocationId)?.trim() || `${runtimeId}:${sessionId}:code.debugCaptureState`, target: { kind: request.target.kind, id: request.target.id?.trim() ?? "", cwd: request.target.cwd?.trim() || undefined }, capture: normalizeCapture(request.capture), dryRun: request.dryRun !== false && context.dryRun !== false, context };
}
function planFrom(n: Normalized): CodeDebugCaptureStatePlan { return { toolName: "code.debugCaptureState", runtimeId: n.runtimeId, sessionId: n.sessionId, invocationId: n.invocationId, target: n.target, permissions: ["debug:read"], capture: n.capture, execution: { dryRun: true, captured: false, unsafeSideEffects: false }, audit: { governanceRequired: true, tapHandoffReady: true }, storage: { logic: { persisted: false }, records: [{ toolName: "code.debugCaptureState" }] } }; }
function empty(n: Normalized): CodeDebugCaptureStateOutput { return { kind: "agentCore.basicTool.code.debugCaptureState.output", runtimeId: n.runtimeId, sessionId: n.sessionId, invocationId: n.invocationId, target: n.target, capture: n.capture, runtimeEntry: { owner: "runtime", port: "BaseToolExecutorPort.debug.captureState", method: "captureState" }, dryRun: true, providerCalled: false, state: "planned", stack: [], variables: [], breakpoints: [], truncated: false, unsafeSideEffects: false }; }
export function planCodeDebugCaptureState(request: CodeDebugCaptureStateRequest = {}): CodeDebugCaptureStateResult { if (request.dryRun === false || request.context?.dryRun === false) return failure("REAL_DEBUG_CAPTURE_NOT_ALLOWED", "planCodeDebugCaptureState only creates a dry-run capture envelope", "governance"); const n = normalize(request); if ("ok" in n) return n; return { ok: true, plan: planFrom(n), events: ["agentCore.basicTool.code.debugCaptureState.planned"] }; }
export async function executeCodeDebugCaptureState(request: CodeDebugCaptureStateRequest = {}): Promise<CodeToolResult<CodeDebugCaptureStateOutput, CodeDebugCaptureStateErrorCode>> {
  const n = normalize(request); if ("ok" in n) return toolFailure(n.error.code, n.error.message, n.error.boundary);
  if (n.dryRun) return { ok: true, toolId: "code.debugCaptureState", output: empty(n), audit: [auditEvent("agentCore.basicTool.code.debugCaptureState.planned", n)], events: ["agentCore.basicTool.code.debugCaptureState.planned"] };
  if (!approved(request.guard, request.governance, n.context.guard)) return toolFailure("GOVERNANCE_REJECTED", "code.debugCaptureState real capture requires an affirmative runtime guard", "governance", n);
  if (request.provider === undefined) return toolFailure("PROVIDER_UNAVAILABLE", "code.debugCaptureState requires runtime debug.captureState support", "provider", n);
  try { const result = await request.provider({ target: n.target, capture: n.capture }, n.context); const vars = (result.variables ?? []).slice(0, n.capture.maxVariables || undefined); return { ok: true, toolId: "code.debugCaptureState", output: { ...empty(n), dryRun: false, providerCalled: true, state: result.state, stack: result.stack ?? [], variables: vars, breakpoints: result.breakpoints ?? [], truncated: (result.variables ?? []).length > vars.length }, audit: [auditEvent("agentCore.basicTool.code.debugCaptureState.completed", n)], events: ["agentCore.basicTool.code.debugCaptureState.completed"] }; } catch { return toolFailure("PROVIDER_FAILURE", "code.debugCaptureState provider failed while reading runtime-owned debug state", "provider", n); }
}
