/*
 * 文件定位：agentCore framework 公共入口。
 * 核心目的：为普通开发者暴露稳定的 Agent authoring、manifest compile 和 runtime kernel API。
 * 边界：不把 runtime.* 深层实现文件作为普通 public API。
 */

export {
  PromptPack,
  PraxisAgent,
  PraxisAgentArchetype,
  append,
  compileAgent,
  endpoint,
  harness,
  inspectAgentManifest,
  loop,
  mainLoop,
  markdown,
  markdownFile,
  model,
  modelFleet,
  overwrite,
  policy,
  prepend,
  replaceLastLines,
  sandbox,
  session,
  statePlane,
  storage,
  tool,
  toolPolicies,
  tools,
  validateAgentManifest,
  type AgentCompileErrorCode,
  type AgentCompileResult,
  type AgentIdentity,
  type AgentManifest,
  type AgentManifestInspection,
  type AgentManifestValidationResult,
  type BaseToolPolicyDecision,
  type BaseToolPolicyMatrixSpec,
  type BaseToolPolicyProfile,
  type BaseToolPolicyRisk,
  type BaseToolPolicyRule,
  type HarnessSpec,
  type FrameworkCoreContractSpec,
  type LoopSpec,
  type MainLoopSpec,
  type ModelEndpointSpec,
  type ModelFleetSpec,
  type ModelSpec,
  type PolicySpec,
  type PraxisAgentClass,
  type PraxisAgentInput,
  type PromptMaterialSource,
  type PromptPackSpec,
  type PromptPatchSpec,
  type SandboxSpec,
  type SessionSpec,
  type StatePlaneSpec,
  type StorageSpec,
  type ToolSpec,
} from "./agent_runtimeImplementation/runtimeAgentManifest.js";

export {
  applyRaxStorageInitPlan,
  createAndApplyStoragePlaneRuntime,
  createRaxStorageLayout,
  createStoragePlaneRuntime,
  planRaxStorageInit,
  resolveRaxHome,
  resolveRaxWorkspace,
  type RaxHomeResolution,
  type RaxPathResolutionError,
  type RaxPathResolutionErrorCode,
  type RaxPathResolutionResult,
  type RaxStorageHomeLayout,
  type RaxStorageInitDirectory,
  type RaxStorageInitPlan,
  type RaxStorageInitResult,
  type RaxStorageLayout,
  type RaxStorageLayoutRefs,
  type RaxStorageWorkspaceLayout,
  type RaxWorkspaceResolution,
  type StoragePlaneRuntime,
  type StoragePlaneRuntimeInput,
  type StoragePlaneRuntimeResult,
} from "./agent_runtimeImplementation/runtime.storagePlane/storagePlaneRuntime.js";

export {
  PraxisRuntimeKernel,
  createPraxisRuntimeKernel,
  type AgentModelCallRecord,
  type AgentRunResult,
  type AgentToolCallRecord,
  type PraxisRuntimeKernelError,
  type PraxisRuntimeKernelErrorCode,
  type PraxisRuntimeKernelOptions,
  type RuntimeApprovalEnvelope,
  type RuntimeApprovalResolution,
  type RuntimeApprovalResolver,
} from "./agent_runtimeImplementation/praxisRuntimeKernel.js";

export {
  createFrameworkInspectionReport,
  type FrameworkDependencyInput,
  type FrameworkInspectionFinding,
  type FrameworkInspectionReport,
  type FrameworkInspectionReportRequest,
  type FrameworkInspectionReportResult,
  type FrameworkProviderReadinessInput,
  type FrameworkPromptPackPreviewInput,
  type FrameworkToolReadinessInput,
} from "./agent_runtimeImplementation/runtime.inspection/frameworkInspectionReport.js";

export {
  baseToolDeveloperCatalogDescriptor,
  baseTools,
  listBaseToolDeveloperCatalog,
  toolSets,
  tryBaseToolById,
  type BaseToolDeveloperCatalogEntry,
  type BaseToolDeveloperLookupResult,
  type BaseToolSpecInput,
  type CodingToolSetOptions,
} from "./agent_runtimeImplementation/runtime.execEngine/baseToolDeveloperCatalog.js";

export {
  baseToolRealityLedgerDescriptor,
  createBaseToolRealityLedger,
  inspectBaseToolReality,
  snapshotBaseToolRealityLedger,
  type BaseToolDependencyRealityStatus,
  type BaseToolDeveloperReadiness,
  type BaseToolExecutorSupportRealityStatus,
  type BaseToolLiveRealityStatus,
  type BaseToolRealityCapabilityClass,
  type BaseToolRealityLedgerEntry,
  type BaseToolRealityLedgerOptions,
  type BaseToolRealityLiveGate,
  type BaseToolRealityProjection,
  type BaseToolRealityStages,
  type BaseToolRealityStageStatus,
  type BaseToolRealityLedgerSnapshot,
  type BaseToolRegistryMountStatus,
  type BaseToolStorageRealityStatus,
} from "./agent_runtimeImplementation/runtime.execEngine/baseToolRealityLedger.js";
