import type { ToolBaseDefinition } from "./types.js";

const objectSchema = (
  properties: Readonly<Record<string, unknown>>,
  required: readonly string[] = [],
): Readonly<Record<string, unknown>> => ({
  type: "object",
  additionalProperties: false,
  properties,
  required,
});

export const TOOL_BASE_CATALOG = [
  {
    id: "shell.run",
    title: "Run Shell Command",
    layer: "core",
    visibility: "model",
    risk: "execute",
    interaction: "execute",
    description: "Run a command through the host shell with runtime-managed sandboxing, approvals, timeouts, and output truncation.",
    inputSchema: objectSchema({
      command: { type: "string" },
      cwd: { type: "string" },
      timeoutMs: { type: "number" },
      reason: { type: "string" },
    }, ["command"]),
    aliases: ["bash", "terminal", "exec"],
    capabilityTags: ["shell", "process", "workspace"],
    requiresRuntimePorts: ["shell", "sandbox", "approval", "output"],
  },
  {
    id: "file.read",
    title: "Read File",
    layer: "core",
    visibility: "model",
    risk: "read",
    interaction: "inspect",
    description: "Read text or metadata from workspace files through runtime path policy.",
    inputSchema: objectSchema({
      path: { type: "string" },
      startLine: { type: "number" },
      endLine: { type: "number" },
      encoding: { type: "string" },
    }, ["path"]),
    aliases: ["read"],
    capabilityTags: ["file", "workspace", "inspect"],
    requiresRuntimePorts: ["filesystem", "pathPolicy", "output"],
  },
  {
    id: "file.write",
    title: "Write File",
    layer: "core",
    visibility: "deferred",
    risk: "write",
    interaction: "mutate",
    description: "Create or replace a workspace file when patch semantics are not appropriate.",
    inputSchema: objectSchema({
      path: { type: "string" },
      content: { type: "string" },
      createOnly: { type: "boolean" },
    }, ["path", "content"]),
    aliases: ["write"],
    capabilityTags: ["file", "workspace", "mutate"],
    requiresRuntimePorts: ["filesystem", "pathPolicy", "approval"],
  },
  {
    id: "file.edit",
    title: "Edit File",
    layer: "core",
    visibility: "deferred",
    risk: "write",
    interaction: "mutate",
    description: "Apply structured local file edits for models that perform better with edit operations than patches.",
    inputSchema: objectSchema({
      path: { type: "string" },
      edits: {
        type: "array",
        items: objectSchema({
          oldText: { type: "string" },
          newText: { type: "string" },
          replaceAll: { type: "boolean" },
        }, ["oldText", "newText"]),
      },
    }, ["path", "edits"]),
    aliases: ["edit"],
    capabilityTags: ["file", "workspace", "mutate"],
    requiresRuntimePorts: ["filesystem", "pathPolicy", "approval"],
  },
  {
    id: "file.search",
    title: "Search Files",
    layer: "core",
    visibility: "model",
    risk: "read",
    interaction: "inspect",
    description: "Search workspace files using runtime-selected fast search backends such as ripgrep.",
    inputSchema: objectSchema({
      query: { type: "string" },
      path: { type: "string" },
      glob: { type: "string" },
      maxResults: { type: "number" },
    }, ["query"]),
    aliases: ["grep", "glob", "rg", "find"],
    capabilityTags: ["file", "workspace", "inspect", "search"],
    requiresRuntimePorts: ["filesystem", "search", "pathPolicy", "output"],
  },
  {
    id: "patch.apply",
    title: "Apply Patch",
    layer: "core",
    visibility: "model",
    risk: "write",
    interaction: "mutate",
    description: "Apply a unified patch to workspace files through runtime validation and approval policy.",
    inputSchema: objectSchema({
      patch: { type: "string" },
      cwd: { type: "string" },
    }, ["patch"]),
    aliases: ["apply_patch", "patch"],
    capabilityTags: ["file", "workspace", "mutate", "diff"],
    requiresRuntimePorts: ["patch", "filesystem", "pathPolicy", "approval"],
  },
  {
    id: "web.search",
    title: "Search Web",
    layer: "core",
    visibility: "model",
    risk: "network",
    interaction: "inspect",
    description: "Search the web for current or grounded information through runtime-managed network policy.",
    inputSchema: objectSchema({
      query: { type: "string" },
      domains: { type: "array", items: { type: "string" } },
      recencyDays: { type: "number" },
    }, ["query"]),
    aliases: ["web_search"],
    capabilityTags: ["web", "grounding", "search"],
    requiresRuntimePorts: ["web", "networkPolicy", "output"],
  },
  {
    id: "web.fetch",
    title: "Fetch Web Page",
    layer: "core",
    visibility: "model",
    risk: "network",
    interaction: "inspect",
    description: "Fetch and extract a web page or remote document through runtime-managed network policy.",
    inputSchema: objectSchema({
      url: { type: "string" },
      maxBytes: { type: "number" },
    }, ["url"]),
    aliases: ["web_fetch", "fetch"],
    capabilityTags: ["web", "grounding", "fetch"],
    requiresRuntimePorts: ["web", "networkPolicy", "output"],
  },
  {
    id: "plan.update",
    title: "Update Plan",
    layer: "core",
    visibility: "model",
    risk: "safe",
    interaction: "inspect",
    description: "Publish or update a structured task plan for the user and runtime surfaces.",
    inputSchema: objectSchema({
      explanation: { type: "string" },
      steps: {
        type: "array",
        items: objectSchema({
          step: { type: "string" },
          status: { type: "string", enum: ["pending", "in_progress", "completed"] },
        }, ["step", "status"]),
      },
    }, ["steps"]),
    aliases: ["todo", "update_plan"],
    capabilityTags: ["plan", "coordination"],
    requiresRuntimePorts: ["plan"],
  },
  {
    id: "user.ask",
    title: "Ask User",
    layer: "core",
    visibility: "model",
    risk: "safe",
    interaction: "ask",
    description: "Pause for user input when assumptions would be risky or materially change the result.",
    inputSchema: objectSchema({
      question: { type: "string" },
      context: { type: "string" },
      choices: { type: "array", items: { type: "string" } },
    }, ["question"]),
    aliases: ["ask_user", "request_user_input"],
    capabilityTags: ["user", "handoff", "coordination"],
    requiresRuntimePorts: ["userInteraction"],
  },
  {
    id: "agent.spawn",
    title: "Spawn Agent",
    layer: "agent",
    visibility: "model",
    risk: "execute",
    interaction: "delegate",
    description: "Delegate an isolated subtask to another runtime-managed agent.",
    inputSchema: objectSchema({
      task: { type: "string" },
      profile: { type: "string" },
      contextRefs: { type: "array", items: { type: "string" } },
    }, ["task"]),
    aliases: ["task", "subagent"],
    capabilityTags: ["agent", "delegate"],
    requiresRuntimePorts: ["agent"],
  },
  {
    id: "agent.message",
    title: "Message Agent",
    layer: "agent",
    visibility: "deferred",
    risk: "safe",
    interaction: "delegate",
    description: "Send a follow-up message to an existing runtime-managed agent.",
    inputSchema: objectSchema({
      agentId: { type: "string" },
      message: { type: "string" },
    }, ["agentId", "message"]),
    capabilityTags: ["agent", "delegate"],
    requiresRuntimePorts: ["agent"],
  },
  {
    id: "agent.wait",
    title: "Wait For Agent",
    layer: "agent",
    visibility: "deferred",
    risk: "safe",
    interaction: "delegate",
    description: "Wait for delegated agent updates or completion.",
    inputSchema: objectSchema({
      agentId: { type: "string" },
      timeoutMs: { type: "number" },
    }),
    capabilityTags: ["agent", "delegate"],
    requiresRuntimePorts: ["agent"],
  },
  {
    id: "skill.load",
    title: "Load Skill",
    layer: "agent",
    visibility: "model",
    risk: "read",
    interaction: "inspect",
    description: "Load a runtime-available skill instruction pack by name or trigger.",
    inputSchema: objectSchema({
      name: { type: "string" },
      trigger: { type: "string" },
    }),
    aliases: ["activate_skill"],
    capabilityTags: ["skill", "context"],
    requiresRuntimePorts: ["skill"],
  },
  {
    id: "context.load",
    title: "Load Context",
    layer: "agent",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Load compact runtime context by stable reference.",
    inputSchema: objectSchema({
      ref: { type: "string" },
      reason: { type: "string" },
    }, ["ref"]),
    capabilityTags: ["context"],
    requiresRuntimePorts: ["context"],
  },
  {
    id: "mcp.use",
    title: "Use MCP Tool",
    layer: "agent",
    visibility: "model",
    risk: "execute",
    interaction: "execute",
    description: "Invoke a mounted MCP tool through runtime governance and schema normalization.",
    inputSchema: objectSchema({
      server: { type: "string" },
      tool: { type: "string" },
      arguments: { type: "object" },
    }, ["server", "tool"]),
    aliases: ["mcp_tool"],
    capabilityTags: ["mcp", "external"],
    requiresRuntimePorts: ["mcp", "approval"],
  },
  {
    id: "mcp.resources",
    title: "Read MCP Resources",
    layer: "agent",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "List resources, list resource templates, read, subscribe to, or unsubscribe from resources exposed by mounted MCP servers.",
    inputSchema: objectSchema({
      server: { type: "string" },
      uri: { type: "string" },
      subscriptionId: { type: "string" },
      action: { type: "string", enum: ["list", "templates", "read", "subscribe", "unsubscribe"] },
    }, ["action"]),
    aliases: ["list_mcp_resources", "list_mcp_resource_templates", "read_mcp_resource", "subscribe_mcp_resource", "unsubscribe_mcp_resource"],
    capabilityTags: ["mcp", "external", "context"],
    requiresRuntimePorts: ["mcp"],
  },
  {
    id: "mcp.prompts",
    title: "Read MCP Prompts",
    layer: "agent",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "List or get prompts exposed by mounted MCP servers.",
    inputSchema: objectSchema({
      server: { type: "string" },
      name: { type: "string" },
      cursor: { type: "string" },
      action: { type: "string", enum: ["list", "get"] },
      arguments: { type: "object" },
    }, ["action"]),
    aliases: ["list_mcp_prompts", "get_mcp_prompt"],
    capabilityTags: ["mcp", "external", "context"],
    requiresRuntimePorts: ["mcp"],
  },
  {
    id: "lsp.query",
    title: "Query Language Server",
    layer: "optional",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Ask a mounted language server for definitions, references, diagnostics, symbols, or rename previews.",
    inputSchema: objectSchema({
      action: { type: "string" },
      path: { type: "string" },
      position: objectSchema({
        line: { type: "number" },
        character: { type: "number" },
      }),
      query: { type: "string" },
    }, ["action"]),
    aliases: ["lsp"],
    capabilityTags: ["code", "lsp", "inspect"],
    requiresRuntimePorts: ["lsp", "filesystem", "pathPolicy"],
  },
  {
    id: "browser.use",
    title: "Use Browser",
    layer: "optional",
    visibility: "deferred",
    risk: "network",
    interaction: "execute",
    description: "Operate a browser session through runtime-controlled navigation, observation, and interaction actions.",
    inputSchema: objectSchema({
      action: { type: "string" },
      url: { type: "string" },
      selector: { type: "string" },
      text: { type: "string" },
    }, ["action"]),
    aliases: ["browser"],
    capabilityTags: ["browser", "web", "interactive"],
    requiresRuntimePorts: ["browser", "networkPolicy", "approval", "output"],
  },
  {
    id: "computer.use",
    title: "Use Computer",
    layer: "optional",
    visibility: "deferred",
    risk: "dangerous",
    interaction: "execute",
    description: "Operate the local desktop through runtime-controlled observe, click, type, and keyboard actions.",
    inputSchema: objectSchema({
      action: { type: "string" },
      target: { type: "string" },
      text: { type: "string" },
    }, ["action"]),
    aliases: ["computer"],
    capabilityTags: ["computer", "desktop", "interactive"],
    requiresRuntimePorts: ["computer", "approval", "sandbox"],
  },
  {
    id: "image.view",
    title: "View Image",
    layer: "optional",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Load an image artifact or file for model-visible visual inspection.",
    inputSchema: objectSchema({
      path: { type: "string" },
      url: { type: "string" },
      detail: { type: "string" },
    }),
    aliases: ["view_image"],
    capabilityTags: ["image", "vision", "inspect"],
    requiresRuntimePorts: ["media", "filesystem", "pathPolicy"],
  },
  {
    id: "image.generate",
    title: "Generate Image",
    layer: "optional",
    visibility: "deferred",
    risk: "network",
    interaction: "generate",
    description: "Generate or edit raster images through runtime-selected media providers and policy checks.",
    inputSchema: objectSchema({
      prompt: { type: "string" },
      referenceRefs: { type: "array", items: { type: "string" } },
      outputRef: { type: "string" },
    }, ["prompt"]),
    aliases: ["imagegen"],
    capabilityTags: ["image", "generation", "media"],
    requiresRuntimePorts: ["media", "approval", "artifact"],
  },
  {
    id: "audio.transcribe",
    title: "Transcribe Audio",
    layer: "optional",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Transcribe speech from an audio or video artifact through runtime-selected providers.",
    inputSchema: objectSchema({
      path: { type: "string" },
      url: { type: "string" },
      language: { type: "string" },
      diarize: { type: "boolean" },
    }),
    aliases: ["transcribe"],
    capabilityTags: ["audio", "transcription", "media"],
    requiresRuntimePorts: ["media", "filesystem", "pathPolicy", "artifact"],
  },
  {
    id: "media.generate",
    title: "Generate Media",
    layer: "optional",
    visibility: "deferred",
    risk: "network",
    interaction: "generate",
    description: "Generate non-image media such as audio, music, speech, or video through runtime-selected providers.",
    inputSchema: objectSchema({
      kind: { type: "string" },
      prompt: { type: "string" },
      outputRef: { type: "string" },
    }, ["kind", "prompt"]),
    capabilityTags: ["media", "generation"],
    requiresRuntimePorts: ["media", "approval", "artifact"],
  },
  {
    id: "memory.use",
    title: "Use Memory",
    layer: "optional",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Search, read, or write runtime memory through explicit policy and user-facing boundaries.",
    inputSchema: objectSchema({
      action: { type: "string", enum: ["search", "read", "write"] },
      query: { type: "string" },
      ref: { type: "string" },
      content: { type: "string" },
    }, ["action"]),
    aliases: ["memory"],
    capabilityTags: ["memory", "context"],
    requiresRuntimePorts: ["memory", "approval"],
  },
  {
    id: "repo.inspect",
    title: "Inspect Repository",
    layer: "optional",
    visibility: "deferred",
    risk: "read",
    interaction: "inspect",
    description: "Return repository metadata, status, branches, diffs, and ownership summaries through runtime git/repo ports.",
    inputSchema: objectSchema({
      action: { type: "string" },
      path: { type: "string" },
      ref: { type: "string" },
    }, ["action"]),
    aliases: ["git", "repo"],
    capabilityTags: ["repo", "git", "inspect"],
    requiresRuntimePorts: ["repo", "filesystem", "pathPolicy"],
  },
  {
    id: "approval.request",
    title: "Request Approval",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only approval handoff used before sensitive tool execution.",
    inputSchema: objectSchema({
      reason: { type: "string" },
      risk: { type: "string" },
      toolId: { type: "string" },
    }, ["reason", "toolId"]),
    capabilityTags: ["governance", "approval"],
    requiresRuntimePorts: ["approval"],
  },
  {
    id: "permission.check",
    title: "Check Permission",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only permission check for scopes, roots, networks, tools, and provider calls.",
    inputSchema: objectSchema({
      scope: { type: "string" },
      target: { type: "string" },
    }, ["scope"]),
    capabilityTags: ["governance", "permission"],
    requiresRuntimePorts: ["permission"],
  },
  {
    id: "sandbox.run",
    title: "Run In Sandbox",
    layer: "runtime",
    visibility: "runtime",
    risk: "execute",
    interaction: "govern",
    description: "Runtime-only sandbox wrapper for commands, code, and risky host operations.",
    inputSchema: objectSchema({
      command: { type: "string" },
      policyRef: { type: "string" },
    }, ["command"]),
    capabilityTags: ["sandbox", "governance"],
    requiresRuntimePorts: ["sandbox"],
  },
  {
    id: "artifact.store",
    title: "Store Artifact",
    layer: "runtime",
    visibility: "runtime",
    risk: "write",
    interaction: "govern",
    description: "Runtime-only artifact storage for files, media, logs, and generated outputs.",
    inputSchema: objectSchema({
      ref: { type: "string" },
      contentType: { type: "string" },
      content: { type: "string" },
    }, ["ref"]),
    capabilityTags: ["artifact", "storage"],
    requiresRuntimePorts: ["artifact"],
  },
  {
    id: "output.truncate",
    title: "Truncate Output",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only output shaping for large command, file, web, and media results.",
    inputSchema: objectSchema({
      text: { type: "string" },
      maxBytes: { type: "number" },
    }, ["text"]),
    capabilityTags: ["output", "context"],
    requiresRuntimePorts: ["output"],
  },
  {
    id: "process.wait",
    title: "Wait Process",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only wait operation for long-running processes started by shell or sandbox ports.",
    inputSchema: objectSchema({
      processId: { type: "string" },
      timeoutMs: { type: "number" },
    }, ["processId"]),
    capabilityTags: ["process", "shell"],
    requiresRuntimePorts: ["process"],
  },
  {
    id: "process.kill",
    title: "Kill Process",
    layer: "runtime",
    visibility: "runtime",
    risk: "dangerous",
    interaction: "govern",
    description: "Runtime-only process termination operation gated by host policy.",
    inputSchema: objectSchema({
      processId: { type: "string" },
      signal: { type: "string" },
    }, ["processId"]),
    capabilityTags: ["process", "shell"],
    requiresRuntimePorts: ["process", "approval"],
  },
  {
    id: "secret.resolve",
    title: "Resolve Secret",
    layer: "runtime",
    visibility: "runtime",
    risk: "dangerous",
    interaction: "govern",
    description: "Runtime-only secret lookup that never exposes raw secret values to model-facing tool schemas.",
    inputSchema: objectSchema({
      ref: { type: "string" },
      purpose: { type: "string" },
    }, ["ref", "purpose"]),
    capabilityTags: ["secret", "governance"],
    requiresRuntimePorts: ["secret"],
  },
  {
    id: "tool.discover",
    title: "Discover Tools",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only discovery of deferred or mounted tools before selectively exposing them.",
    inputSchema: objectSchema({
      query: { type: "string" },
      layer: { type: "string" },
    }),
    capabilityTags: ["tool", "discovery"],
    requiresRuntimePorts: ["toolRegistry"],
  },
  {
    id: "tool.describe",
    title: "Describe Tool",
    layer: "runtime",
    visibility: "runtime",
    risk: "safe",
    interaction: "govern",
    description: "Runtime-only detailed description lookup for deferred or mounted tools.",
    inputSchema: objectSchema({
      toolId: { type: "string" },
    }, ["toolId"]),
    capabilityTags: ["tool", "discovery"],
    requiresRuntimePorts: ["toolRegistry"],
  },
] satisfies readonly ToolBaseDefinition[];

export const TOOL_BASE_RUNTIME_CATALOG = [
  "approval.request",
  "permission.check",
  "sandbox.run",
  "artifact.store",
  "output.truncate",
  "process.wait",
  "process.kill",
  "secret.resolve",
  "tool.discover",
  "tool.describe",
] as const;
