import { defineAgentCoreContractTest } from "../../../../../agentCoreContractTestHelper.js";
import assert from "node:assert/strict";
import test from "node:test";
import {
  generateShellScriptPlan,
  shellScriptGenerationDescriptor,
} from "../../../../../../../src/agentCore/agent_executionEngine/basic_toolLayer/baseTools/shellBase/shellGeneration/shell.scriptGeneration.js";

defineAgentCoreContractTest({
  sourcePath: "Praxis_Agent_Architecture/src/agentCore/agent_executionEngine/basic_toolLayer/baseTools/shellBase/shellGeneration/shell.scriptGeneration.ts",
  docPath: "Praxis_Agent_Architecture/docs/agentCore/agent_executionEngine/basic_toolLayer/baseTools/shellBase/shellGeneration/shell.scriptGeneration.md",
  testFileUrl: import.meta.url,
});

test("generateShellScriptPlan creates a dry-run shell script envelope", () => {
  const result = generateShellScriptPlan({
    target: {
      scriptName: "smoke.sh",
      shell: "bash",
      workingDirectory: "/repo/app",
      environment: { NODE_ENV: "test" },
      commands: ["npm test"],
      notes: ["generated by agentCore shell primitive"],
    },
    context: {
      invocationId: "script-1",
      grantedPermissions: ["shell:script:generate"],
      allowedWorkingDirectories: ["/repo"],
    },
  });

  assert.equal(result.ok, true);
  assert.equal(shellScriptGenerationDescriptor.defaultDryRun, true);
  if (!result.ok) {
    return;
  }

  assert.equal(result.output.target.shell, "bash");
  assert.match(result.output.script, /^#!\/usr\/bin\/env bash/);
  assert.match(result.output.script, /cd '\/repo\/app'/);
  assert.match(result.output.script, /export NODE_ENV='test'/);
  assert.equal(result.output.dryRun, true);
  assert.equal(result.output.executionBlocked, true);
  assert.equal(result.output.unsafeSideEffects, false);
  assert.deepEqual(result.events, ["basicTool.shell.scriptGeneration.dryRun"]);
});

test("generateShellScriptPlan rejects missing commands, scope, permission, and real execution", () => {
  const missing = generateShellScriptPlan();
  assert.equal(missing.ok, false);
  if (!missing.ok) {
    assert.equal(missing.error.code, "MISSING_COMMANDS");
    assert.equal(missing.error.boundary, "input");
  }

  const scope = generateShellScriptPlan({
    target: { workingDirectory: "/outside", commands: ["pwd"] },
    context: { allowedWorkingDirectories: ["/repo"], grantedPermissions: ["shell:script:generate"] },
  });
  assert.equal(scope.ok, false);
  if (!scope.ok) {
    assert.equal(scope.error.code, "SCOPE_REJECTED");
    assert.equal(scope.error.boundary, "scope");
  }

  const permission = generateShellScriptPlan({
    target: { commands: ["pwd"] },
    context: { grantedPermissions: [] },
  });
  assert.equal(permission.ok, false);
  if (!permission.ok) {
    assert.equal(permission.error.code, "PERMISSION_DENIED");
    assert.equal(permission.error.boundary, "permission");
  }

  const real = generateShellScriptPlan({
    target: { commands: ["pwd"] },
    context: { dryRun: false },
  });
  assert.equal(real.ok, false);
  if (!real.ok) {
    assert.equal(real.error.code, "REAL_EXECUTION_BLOCKED");
    assert.equal(real.error.boundary, "contract");
  }
});
